name: Docker Image CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'develop'
        type: choice
        options:
        - main
        - develop
env:
  EX_BRANCH: ${{ github.event.inputs.BRANCH || 'develop' }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: $EX_BRANCH
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: get
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag Name: "${{github.event.release.tag_name}}
      - name: CheckTag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aescanero/micropki/${{ env.RELEASE_VERSION }}:latest
    
